package models;

/**
 * Created by HP PC on 5/20/2016.
 */
public enum ObstacleType {
    SIDE_OBSTACLE,
    BLINKING_SIDE_OBSTACLE,
    ROTATING_OBSTACLE,
    POSITION_OBSTACLE,
    ROTATING_POSITION_OBSTACLE,
    ROTATING_SIDE_OBSTACLE
}
